model:
  embed_size: 256
  hidden_size: 512
  num_layers: 3
  seq_length: 256

training:
  batch_size: 128
  learning_rate: 0.001
  epochs: 20
  val_split: 0.1
  resume: false
  checkpoint_interval: 2

paths:
  checkpoint_dir: checkpoints
  plots_dir: plots
  data_path: data/input.txt
  model_save_path: poetry_lstm.pth
  plot_save_path: training_metrics.png
